#include <bits/stdc++.h>
using namespace std;
using ll = long long; using ull = unsigned long long;using ld = double; 
using vi = vector<int>; using vvi = vector<vi>;
using vl = vector<ll>; using vvl = vector<vl>;
using pl = pair<ll,ll>; using vpl = vector<pl>; using vvpl = vector<vpl>;
using pi = pair<int,int>; using vpi = vector<pi>;using vvpi = vector<vpi>;
using vb = vector<bool>; using vvb = vector<vb>;

#if defined(LOCAL) && __has_include("debug.h")
#include "debug.h"
#else
#define debug(...)
#endif

#define endl '\n' 
#define F first 
#define S second 
#define all(x) begin(x), end(x)
#define rall(x) rbegin(x), rend(x)
#define pb push_back
#define MIN(a) *min_element(all(a));
#define MAX(a) *max_element(all(a));

const vvi dirs = {{-1,0},{1,0},{0,-1},{0,1}};
constexpr ll INF = 4e18; 
constexpr ld EPS = 1e-9; 
constexpr ll MOD = 1e9+7;


// NOTE:
// diksjtra with modulus ? 
// can we compress roads from 2^i to i? 
// eveyr road has a distinct distance 
// and no road is taken tweice
// that means the sum of i maps to 2i nicely, in sorted order
// becaise i < (i+1) and 2i < (2i+1)
// so instead we need we can just construct the normal sunm
// then say sum = 6 = 101 
// 1 2 3 4 5 
// 1 2 4 8 16 
//
// oh there is a shift by one 
// 1 2 3 4 5 
// 0 1 2 4 8 
// normally 
//
// so we just make the anwe +1 
// hmm 
// 2a + 2b + 2c + 2d 
// the indexes are unique yes, 
// but how do we compress it? 
// im choosing a subset of [1, M]
// the stupid idea is just 1 << M 
// thts literally no difference from input 
// and its most optimal 
// sum is not distnct 
// 10  = 4 + 6 
//     = 1 + 9 
//
//  one think we can notice is max path length is N 
//  the sum dont matter, but its the MAX road of the path 
//  however if we only keep track of MAX, its not fast enough to construct
//  the paths generated by dijsktra always form a tree though 
//  so we can use thaat tree and just reconstruct 


ll binpowmod(ll a, ll b, ll m){
    a %= m;
    ll res = 1;
    while(b > 0){
        if (b & 1) res = res * a % m;
        a = a  * a % m;
        b >>=1;
    }
    return res;
}


//  NOTE:
// this is 100%^ dijsktra 
// we just need to find a better way to compress or covert the weights 
// can i juse logs 
//
// i need to be careful 
// the SP is determined by the SMALLEST max edge used in the path 
// i CAN construct dijkstra with this but, the tree not really? 
//
// my solution  is wrong its not just the max EDGE, its the either sequence minimized 
// that means my distance need to be pq??? 
// that makes no snese though 
// i cant just store the low "MAX" path 
// its like idk 
//
// we can use the dijsktra invaraint ot something 
// worst case sequence is a linked list tree 
// the thing can scale up to very big 
//
//  
//  consider ways to compress 
//  NOTE: 
//  (1) lexical ordering 
//      -> the path from START to i must have the smallest MAX node. if max is the same we go the next next 
//      -> not really feasible
//
//
// (2) big integer 
//  -> too slow i think 
//
//  (3) logs?? 
//

void solve(){
    int n, m;
    cin >> n >> m;
    vvpl g(n);
    vector<map<int,int>> mp(n);
    ll mod = 998244353;
    for (int i = 0; i < m ;i++){
        int u,v;
        cin >> u >> v;
        u--, v--;
        g[u].pb({v, i + 1});
        g[v].pb({u, i + 1});
        mp[u][v] = i;
        mp[v][u] = i;
    }
    debug(g);
    vl dist(n, INF);
    dist[0] = 0ll;
    vpl trace(n, {-1,-1});
    priority_queue<pl, vector<pl>, greater<pl>> pq;
    pq.push({0,0});
    while(!pq.empty()){
        auto [wt, u] = pq.top(); // wt -> max path used to go to u
        debug(wt,u);
        pq.pop();
        if (dist[u] < wt) continue;
        for (auto& [v , dv]: g[u]){
            // ll nw = dist[u] + dv;
            // ll nw = max(wt, dv);
            ll nw = dv;
            if (nw < dist[v]){ // this makes no sense 
                dist[v] = nw; // 
                pq.push({ nw, v});
                trace[v] = {u, nw};
            }
        }
    }
    debug(dist);

    // construct the tree 
    vl res(n, -1ll);
    debug(res);
    debug(trace);
    vvpl f(n);
    for (int i = 1; i < n; i++){
        ll p = trace[i].F;
        ll w = trace[i].S;
        if (w == -1) continue;
        f[p].pb({i, w});
        f[i].pb({p, w});
    }



    debug(f);
    auto go = [&](auto& go, int u, int p, ll tot) -> void{
        debug(u ,p);
        res[u] = tot;
        for (auto& [v, wt]: f[u]){
            // i need to ignore wt 
            // its not the right weight 
            //
            if (v ==p) continue;
            debug(u, v);
            ll z = mp[u][v];
            ll add = binpowmod(2ll, z , mod);
            tot = (tot + add) % mod;
            go(go, v, u, tot);
        }
    };

    go(go, 0, -1, 0ll);
    for (int i = 1; i < n; i++){
        cout << res[i] << " ";
    }
    cout << endl;


};

int main(){
    ios::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
    // freopen("file.in","r",stdin);
    // freopen("file.out","w",stdout);
    int T =1;
    cin >> T; 
    while(T--) solve();
    return 0;
}
